module.exports = {
    src: 'client',
    dist: 'dist',
    e2e: 'e2e',
    port: 3000,
    livereloadPort: 35729,
    htmlFiles: ['./client/**/**.html', '!client/jspm_packages/**'],
    jsFiles: ['./client/src/**/**.js'],
    scssFiles: ['./client/**/**.scss'],
    jsLinters: true,
    cssLinters: true,
    htmlLinters: true,
    watchJs: false,
    watchCss: true,
    watchHtml: false,
    liveReload: false,
    karmaAutoWatch: true,
    karmaSingleRun: false,
    karmaBrowser: ['Chrome', 'PhantomJS'],
};
